name: flutter_application_1
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

  english_words: ^4.0.0
  provider: ^6.0.0
  google_maps_flutter: ^2.9.0
  google_maps_flutter_web: ^0.5.10
  location: ^5.0.0
  cloud_firestore: ^5.4.4
  firebase_core: ^3.6.0
  http: ^1.2.2
  flutter_polyline_points: ^2.0.0
  geolocator: ^13.0.1
  shared_preferences: ^2.3.3
  dio: ^5.7.0
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
